### ISSUE TITLE
"Debugging the compiler"

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rustc-guide#11]
This section should talk about the various tips and tricks for debugging the compiler, as well as perhaps some amount of "debug log conventions". It doesn't necessarily have to be a *super* long section, but here are some of the things I can think of:

- [x] How to use `RUST_LOG` and `config.toml` first and foremost (overlaps with https://github.com/rust-lang-nursery/rustc-guide/issues/8)
- [x] Some of the handy `-Zflags`:
    - [x] example: `-Ztreat-err-as-bug`, which causes errors to be reported as bugs. Useful when you are debugging an error that should not be happening because you can use `RUST_BACKTRACE=1` then to get a backtrace of where the error was reported; also avoids dumping out more logs than you need.
    - [x] example: `-Zunpretty=hir-tree`, which will dump out the HIR
    - [x] example: `-Zverbose`, which dumps out extra 
    - [x] see `-Zhelp` for more
- [x] Conventions for logs ("loosely followed")
    - [x] Use `{:?}` most of the time in debug logs
    - [x] I tend to use `debug!("foo(...)")` at the start of a function `foo` and `debug!("foo: ...")` or logs within that function (- nikomatsakis)
- [x] Options to try and correlate node-ids and def-ids with the source
    - [x] e.g., `--pretty expanded,identified`
- [x] Options to dump the MIR
    - [x] `-Zdump-mir` and `-Zdump-mir-graphviz`

**Comment by nikomatsakis** [comment]
I just noticed that there is a page on forge on this topic:

https://forge.rust-lang.org/debugging.html

So, as a start, moving that content into the rustc-guide and removing the page from forge would be easy enough!

**Comment by cg-cnu** [comment]
Hey @nikomatsakis A rust beginner here and first time contributor to rust project. Might need some help in making the PR, but definitely interested in putting the time and working on it. Can I work on it 🙂

**Comment by gnzlbg** [comment]
I just tried to debug the compiler using `debug!`. There is such a huge amount of noise that's pretty much useless. Tons of lines of:

```
DEBUG 2019-02-12T02:35:41Z: syntax::source_map: byte pos BytePos(0) is on the line at byte pos BytePos(0)
DEBUG 2019-02-12T02:35:41Z: syntax::source_map: char pos CharPos(0) is on the line at char pos CharPos(0)
DEBUG 2019-02-12T02:35:41Z: syntax::source_map: byte is on line: 1
DEBUG 2019-02-12T02:35:41Z: syntax::source_map: byte pos BytePos(0) is on the line at byte pos BytePos(0)
DEBUG 2019-02-12T02:35:41Z: syntax::source_map: char pos CharPos(0) is on the line at char pos CharPos(0)
DEBUG 2019-02-12T02:35:41Z: syntax::source_map: byte is on line: 1
```

I wish there was an easy way to just use `eprintln!` or something without noise. Or do I have to go through the compiler and remove all `debug!` statements to be able to see the output of mine ?

**Comment by Mark-Simulacrum** [comment]
Generally the intent is to be more specific than just `RUST_LOG=syntax=debug`; where you trying to debug something in `syntax::source_map` specifically? Otherwise I would expect you to not include it in the logging at all...

**Comment by gnzlbg** [comment]
> Generally the intent is to be more specific than just RUST_LOG=syntax=debug; where you trying to debug something in syntax::source_map specifically? No, it was late and I forgot that you could `RUST_LOG=modulename` too. Maybe it would be worth calling that out specifically in the guide.

**Comment by eddyb** [comment]
We should *really* tell people to use `RUST_LOG=rustc_foo::bar::baz`, with the smallest module(s) (comma-separated if multiple) necessary for the `debug!`s they want.

IIRC `RUST_LOG=syntax=debug` and `RUST_LOG=syntax` does the same thing, but I could be wrong. Either way, the logging level *should not* be the important bit, but rather the relevant module.
