### ISSUE TITLE
"Conventions used in the compiler"

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rustc-guide#12]
Some of this material exists already scattered about, and/or maybe this overlaps with the glossary, but I think it'd be helpful to try and capture some common conventions.

Here are some things I'm thinking about:

- [x] How to format code (#47)
    - [x] Um... kind of a mess. Hopefully we'll move to rustfmt.
- [x] Naming conventions (maybe this should just be in the glossary, actually?)
    - [x] the `cx` suffix -- short for "context"
    - [x] `'tcx` and `'gcx`  -- mostly direct elsewhere for detailed explanation?
- [x] When to add/avoid adding dependencies from crates.io? What is the vetting process?
    - [x] Whitelisting?
- [ ] What else?

**Comment by mark-i-m** [comment]
cc #47 (adds conventions.md)
