### ISSUE TITLE
Move relevant content from the forge

### ISSUE THREAD

**Issue by mark-i-m** [rust-lang/rustc-guide#133]
Currently, the forge has a lot of useful content that could be moved over.

It would be good to move each of these over to the relevant part of the rustc guide and delete the corresponding forge page (by making a PR on https://github.com/rust-lang-nursery/rust-forge).

- [x] x.py: https://github.com/rust-lang-nursery/rust-forge/blob/master/x-py.md (#130)
- [x] Debugging: https://github.com/rust-lang-nursery/rust-forge/blob/master/debugging.md (#113)
- [x] Stabilization guide: https://github.com/rust-lang-nursery/rust-forge/blob/master/stabilization-guide.md (#262)
- [ ] Compiler Diagnostics: https://github.com/rust-lang-nursery/rust-forge/blob/master/rustc-diagnostic-code.md
- [ ] Compiler Bug Fix Procedure: https://github.com/rust-lang-nursery/rust-forge/blob/master/rustc-bug-fix-procedure.md
- [ ] Profiling queries: https://github.com/rust-lang-nursery/rust-forge/blob/master/profile-queries.md
- [x] Implementing new features: https://github.com/rust-lang-nursery/rust-forge/blob/master/feature-guide.md (#98)
- [ ] ~Infrastructure: https://github.com/rust-lang-nursery/rust-forge/blob/master/infrastructure.md~
- [ ] ~Backporting patches: https://github.com/rust-lang-nursery/rust-forge/blob/master/beta-backporting.md~

EDIT: according to https://github.com/rust-lang-nursery/rustc-guide/issues/133#issuecomment-429571177

**Comment by benbrandt** [comment]
Is this still needed? I'd be happy to help with this!

**Comment by pietroalbini** [comment]
About the infra & backporting pages, I think those should be kept on the forge: those are used mostly by the infra/release teams, not by rustc contributors.

**Comment by pietroalbini** [comment]
@rajcspsg about the stabilization guide, [there is additional content in a forge PR](https://github.com/rust-lang-nursery/rust-forge/pull/125).

**Comment by mark-i-m** [comment]
@rajcspsg That would be great :)

How about a new chapter after the closing conventions chapter?

**Comment by rajcspsg** [comment]
@mark-i-m could you please provide me more details on conventions chapter?

**Comment by mark-i-m** [comment]
@rajcspsg I was thinking of something like this:

```diff
  # Summary

  - [About this guide](./about-this-guide.md)
  - [About the compiler team](./compiler-team.md)
  - [How to build the compiler and run what you built](./how-to-build-and-run.md)
      - [Build and Install distribution artifacts](./build-install-distribution-artifacts.md)
      - [Documenting Compiler](./compiler-documenting.md)
  - [Coding conventions](./conventions.md)
+ - [Stabilizing Features](./stabilization.md)
  - [Walkthrough: a typical contribution](./walkthrough.md)
  - [The compiler testing framework](./tests/intro.md)
  - [The compiler testing framework](./tests/intro.md)
```

Does that answer your question?

**Comment by rajcspsg** [comment]
Yeah. I got it now :) 
Thanks @mark-i-m @pietroalbini 
I will go through the documentation and let you know if I have any questions.

**Comment by rajcspsg** [comment]
@mark-i-m Can I take Implementing new features part of this issue?

**Comment by mark-i-m** [comment]
@rajcspsg I also forgot about  #98. Do you mind also adding the things Niko mentions in that issue as part of your PR?

**Comment by rajcspsg** [comment]
@mark-i-m Sure I will do that !!!

**Comment by rajcspsg** [comment]
@mark-i-m can I work on Compiler Bug Fix Procedure(5th in the list) ?

**Comment by mark-i-m** [comment]
cc @spastorino @nikomatsakis

@rajcspsg I think there are some ongoing discussions about changing the role of the forge, but I am out of town this week so I don’t know what was decided. Perhaps @spastorino can advise?

**Comment by spastorino** [comment]
The idea is that forge should be linked from Rust website and be mainly about procedures. rustc-guide should be pretty focused on "what you need to hack on rustc".

@rajcspsg if you're interested in contributing to rustc-guide in general, I'd recommend you to join Zulip and visit this stream https://rust-lang.zulipchat.com/#narrow/stream/196385-t-compiler.2Fwg-learning

**Comment by mark-i-m** [comment]
@spastorino It seems like the 3 remaining topics in the OP checklist are still relevant and should be moved to the guide. Do you agree?

**Comment by spastorino** [comment]
@mark-i-m yes :+1:, do you want to create issues for them?. I'm planning on starting one or more `Project` to track some things in a different way but from `Project` I can link to all these issues we are talking about.

**Comment by mark-i-m** [comment]
@spastorino I guess I'm not sure. Do we want to make the issues that fine-grained? I'm wary of having information in too many places, as it will be hard to keep everything up to date.

**Comment by spastorino** [comment]
@mark-i-m I think you're right. I'd leave the checklist as is in this issue and not open more issues.
