### ISSUE TITLE
tracking issue for documenting chalk and the trait system 

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rustc-guide#137]
We have some great docs on the trait system already (if I do say so myself 😉) but there's lots of room for improvement. This issue exists to track ideas and try to stay organized.

- [x] Update rustc guide with new rules for GATs (cc @tmandry, @scalexm)

**Comment by mark-i-m** [comment]
Might be good to link to this talk by @sunjay somewhere: https://www.youtube.com/watch?v=rZqS4bLPL24

It's a great intro :)

**Comment by mark-i-m** [comment]
This thread doesn't seem to be very useful, so I will close it to keep the tracker clean.
