### ISSUE TITLE
Document stability attributes?

### ISSUE THREAD

**Issue by dwijnand** [rust-lang/rustc-guide#241]
I was trying to hack in libcore and when compiling it I got:

```
error: This node does not have a stability attribute
```

and couldn't find anything detailing stability attributes.  Should that info live here?

**Comment by dwijnand** [comment]
There's some detail in https://github.com/rust-lang/rust/blob/1.30.1/src/libsyntax/attr/builtin.rs#L104-L123.

**Comment by mark-i-m** [comment]
@dwijnand We now have https://rust-lang.github.io/rustc-guide/stability.html

I will close this issue, but feel free to reopen or create a new issue.
