### ISSUE TITLE
Clarify the meaning of hir::Ty

### ISSUE THREAD

**Issue by euclio** [rust-lang/rustc-guide#244]
In the [Allocating and Working with Types section](https://github.com/rust-lang/rustc-guide/blob/master/src/ty.md#allocating-and-working-with-types), it mentions that `ty::Ty` should not be confused with `Ty` in the HIR. How are they different?

**Comment by mark-i-m** [comment]
hir::Ty is more of a syntactic construct representing the syntax of a type. ty::Ty represents the semantics of a type, e.g. for type checking.

**Comment by eddyb** [comment]
Another way to think about it is every time you write a type, e.g. `()`, it gets its own `ast::Ty` and `hir::Ty` nodes (with IDs and source information), whereas the `Ty` is always exactly one (`ty::Tup([])`).

**Comment by mark-i-m** [comment]
fixed in #530
