### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by mark-i-m** [rust-lang/rustc-guide#293]
@Mark-Simulacrum It appears the following is returning error 500: https://buildbot2.rust-lang.org/homu/

Do you know what the problem could be?

**Comment by pietroalbini** [comment]
This happened after rustlings homu was deployed, and afaik it was never fixed. Maybe you can take a look at the server?

**Comment by mark-i-m** [comment]
What do you mean by “take a look at yhr server”?

**Comment by pietroalbini** [comment]
The link *should* be alive, I asked Mark to check if there is something wrong on central station.

**Comment by pietroalbini** [comment]
Duplicate of https://github.com/rust-lang/rust/issues/59475

**Comment by mark-i-m** [comment]
I would like to leave this open so I don't forget to (at least temporarily) remove the link from the guide.

**Comment by Mark-Simulacrum** [comment]
Well, https://buildbot2.rust-lang.org/homu/ is fixed now it seems after redeploying.
