### ISSUE TITLE
Update cfg(stage0) references to cfg(bootstrap) instead

### ISSUE THREAD

**Issue by scottmcm** [rust-lang/rustc-guide#334]
https://github.com/rust-lang/rustc-guide/blob/master/src/stabilization_guide.md#removing-existing-uses-of-the-feature-gate still mentions `#![cfg_attr(stage0, feature(XXX))]`, but as of https://github.com/rust-lang/rust/pull/61494, it's `bootstrap` instead of `stage0`.

**Comment by JohnTitor** [comment]
It seems this is fixed in #346.
