### ISSUE TITLE
async-await implementation plans

### ISSUE THREAD

**Issue by amanjeev** [rust-lang/rustc-guide#352]
Video: https://www.youtube.com/watch?v=xe2_whJWBC0

This issue has been assigned to @amanjeev via [this comment](https://github.com/rust-lang/rustc-guide/issues/352#issuecomment-506102710).

**Comment by spastorino** [comment]
Closing this one in favor of https://github.com/rust-lang/rustc-guide/issues/372 because that issue lives inside a project now.
