### ISSUE TITLE
async-await region inferencer 

### ISSUE THREAD

**Issue by amanjeev** [rust-lang/rustc-guide#353]
Video: https://www.youtube.com/watch?v=hlOxfkUDLPQ

This issue has been assigned to @amanjeev via [this comment](https://github.com/rust-lang/rustc-guide/issues/353#issuecomment-506102986).

**Comment by spastorino** [comment]
Closing this one in favor of https://github.com/rust-lang/rustc-guide/issues/373 because that issue lives inside a project now.
