### ISSUE TITLE
Universes and Lifetimes

### ISSUE THREAD

**Issue by amanjeev** [rust-lang/rustc-guide#354]
Video: https://www.youtube.com/watch?v=iV1Z0xYXkck

This issue has been assigned to @amanjeev via [this comment](https://github.com/rust-lang/rustc-guide/issues/354#issuecomment-506103156).

**Comment by spastorino** [comment]
Closing this one in favor of https://github.com/rust-lang/rustc-guide/issues/374 because that issue lives inside a project now.
