### ISSUE TITLE
Transcribe the Compiler Lecture Representing types in rustc

### ISSUE THREAD

**Issue by spastorino** [rust-lang/rustc-guide#375]
Video: https://www.youtube.com/watch?v=c01TsOsr3-c

This issue has been assigned to @igaray via [this comment](https://github.com/rust-lang/rustc-guide/issues/375#issuecomment-506992148).

**Comment by mark-i-m** [comment]
@spastorino Is this a duplicate of https://github.com/rust-lang/rustc-guide/pull/348?

**Comment by spastorino** [comment]
Yes, this is the issue, #348 is the PR.
