### ISSUE TITLE
Add compiler lectures series links to an appendix

### ISSUE THREAD

**Issue by spastorino** [rust-lang/rustc-guide#378]
Maybe that could live here https://rust-lang.github.io/rustc-guide/appendix/bibliography.html ? and that be called Rusc resources? or could be even a new Appendix.

/cc @mark-i-m

**Comment by mark-i-m** [comment]
I feel that they are distinct enough to be different Appendices. The Bibliography doesn't really contain much that is directly useful for learning how rustc works, whereas the lectures do.

**Comment by spastorino** [comment]
@mark-i-m :+1: then to use a new appendix for this.
