### ISSUE TITLE
429 Too Many Requests

### ISSUE THREAD

**Issue by mark-i-m** [rust-lang/rustc-guide#385]
Recently a bunch of CI failures have occurred with this error, mostly from YouTube. Not sure what the solution is. I'm also not sure if this is Travis or YouTube...

@Mark-Simulacrum @pietroalbini do you know if this would be mitigated by moving to Azure?

**Comment by Mark-Simulacrum** [comment]
Do you have links to some of these CI failures? Are you intentionally contacting YouTube?

**Comment by shepmaster** [comment]
Is the link checker still active?

**Comment by mark-i-m** [comment]
https://travis-ci.com/rust-lang/rustc-guide/builds/118875063

https://travis-ci.com/rust-lang/rustc-guide/builds/119000366

https://travis-ci.com/rust-lang/rustc-guide/builds/118874560

There are a few more I think.

We link to the compiler lecture series videos on YT. These failures are from the linkchecker attempting to contact YT and failing with 429.

**Comment by pietroalbini** [comment]
Hmm, does linkchecker set a browser user agent?

**Comment by mark-i-m** [comment]
No idea... cc @Michael-F-Bryan

**Comment by Michael-F-Bryan** [comment]
I don't believe we set a user agent. The validator [just calls `reqwest::get()`](https://github.com/Michael-F-Bryan/mdbook-linkcheck/blob/6ac54352d029ec9288d3503d6c27afc62836653a/src/validation.rs#L36) without doing anything fancy.

**Comment by mark-i-m** [comment]
For now, I am just going to blacklist yt feom the linkchecker because CI has been down for a while.

**Comment by mark-i-m** [comment]
We haven't seen this in a while, so I am closing...

**Comment by camelid** [comment]
This has been occurring (spuriously) again. Can we ignore `429 Too Many Requests` errors in linkcheck? (See #885 for some discussion.)
