### ISSUE TITLE
Broken link in compiler-team section

### ISSUE THREAD

**Issue by JohnTitor** [rust-lang/rustc-guide#386]
In [compiler-team section](https://github.com/rust-lang/rustc-guide/blob/master/src/compiler-team.md#expert-map), there is [a broken link](https://github.com/rust-lang/compiler-team/blob/master/experts/MAP.md). I'd like to update this but should we wait for the team to deploy their website to gh-pages?

**Comment by mark-i-m** [comment]
I think we can just link to the new TOML file. We can update the link later.

**Comment by JohnTitor** [comment]
@mark-i-m I see and opened #387.
