### ISSUE TITLE
Explain what interning means

### ISSUE THREAD

**Issue by Nashenas88** [rust-lang/rustc-guide#419]
At the bottom of https://rust-lang.github.io/rustc-guide/the-parser.html, the phrase "interns identifiers" is used. But to me, its meaning wasn't clear on first read-through. I checked in Zulip::/t-compiler/help and got back : "It means that you are not creating a heap allocation for an identifier every time, but instead have a global table where they are stored and deduplicated. You then just need to store the index into the global table whenever you have an identifier" from @oli (oliobk?). It would be helpful to have this explained early on (and maybe a link back to the definition in later uses?)

**Comment by spastorino** [comment]
I think it would be great to have this explained, perhaps starting with what @oli-obk has mentioned would be great.

**Comment by nnethercote** [comment]
https://en.wikipedia.org/wiki/String_interning could be a useful link.

**Comment by feroldi** [comment]
@eddyb explained quite a bit of it here: https://github.com/feroldi/oxide/issues/1#issuecomment-523002973

**Comment by mark-i-m** [comment]
I would actually prefer for us to just so this, add it is a common question

**Comment by mark-i-m** [comment]
We also have some discussion in the upcoming #530 ... I think we should move all of these into a chapter about interning and arenas...

**Comment by spastorino** [comment]
@mark-i-m agreed, let's wait for Niko review, merge #530 and then maybe start moving some things around.
