### ISSUE TITLE
hard-to-parse sentence in Updating LLVM

### ISSUE THREAD

**Issue by tshepang** [rust-lang/rustc-guide#440]
There is missing text here...
> Push this update to the same branch name of the llvm-project submodule to the of the rust-lang/compiler-rt repository.

**Comment by mark-i-m** [comment]
Is this still applicable? I can't seem to find that sentence anywhere...

**Comment by tshepang** [comment]
Made obsolete by cc34e4a4c9fbaf2ca0d501e87c84c31943539362
