### ISSUE TITLE
"Testing infrastructure" isn't up-to-date

### ISSUE THREAD

**Issue by PotHix** [rust-lang/rustc-guide#500]
It seems the [documentation for the testing infrastructure](https://github.com/rust-lang/rustc-guide/blob/master/src/tests/intro.md#testing-infrastructure) is misleading. I can see the tests on Travis and AppVeyor ran 3 months ago.

I believe it's related to the migration to Azure Pipelines, but not entirely sure to contribute.

Either way, the links available for Travis and AppVeyor are not useful currently, so it's certaily an issue.

**Comment by JohnTitor** [comment]
Good catch! Indeed, we should replace them with Azure Pipelines'.

**Comment by PotHix** [comment]
@JohnTitor do we have more info about that available anywhere? I can try to submit a PR for it.

**Comment by JohnTitor** [comment]
We should update it as follows:

- The sentence `Travis will automatically launch a build that will run all tests on a single configuration (x86-64 linux)` should be `Azure Pipelines will automatically [...] all tests on some configurations (x86_64-gnu-llvm-6.0 linux. x86_64-gnu-tools linux, mingw-check linux)`
  - The Azure Pipelines' link should probably point to https://dev.azure.com/rust-lang/rust/ or https://dev.azure.com/rust-lang/rust/_build
- The sentence `When a PR is approved, it goes into a queue where merges are tested one at a time on a wide set of platforms using Travis and Appveyor (currently over 50 different configurations).` should be `[...] on a wide set of platforms using Azure Pipelines (currently over 50 different configurations).`
  - I'm not sure about the number of configurations but I guess it is unchanged

CC: @spastorino

**Comment by PotHix** [comment]
Proposed a PR with the changes mentioned here. I can see there is another reference to Travis on `Testing on emulators`, but I'm not sure if we're still using that setup. Please let me know if I should just change to Azure Pipelines or if it should change entirely.

**Comment by mark-i-m** [comment]
TBH, I'm not sure. I think your current PR is good though. If we discovered more we can do that change in another PR
