### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by shika-blyat** [rust-lang/rustc-guide#591]
In the query.md file:
https://github.com/rust-lang/rustc-guide/blob/master/src/query.md
the first link (which should point to the high level overview of rustc page) is broken. Easy to fix but i don't know which link  exactly it is supposed so i will let someone do a PR to fix/fix it myself if someone tells me which link it's supposed to be.

**Comment by mark-i-m** [comment]
Hi @shika-blyat :)

Thanks for the report. The link seems to work for me.

If you are viewing on github, the links might not work properly. I would recommend the hosted version here instead: https://rust-lang.github.io/rustc-guide/query.html

**Comment by shika-blyat** [comment]
Well the problem was just coming from the link extension, so the PR above should fix it :)

**Comment by shika-blyat** [comment]
Given what JohnTitor said, i'll close this issue
