### ISSUE TITLE
Wrong variable name in query-evaluation-model-in-detail.md

### ISSUE THREAD

**Issue by SarthakSingh31** [rust-lang/rustc-guide#592]
https://github.com/rust-lang/rustc-guide/blob/9b3803d35d0e9ee80c0b42ee58ed472b16f06ea8/src/queries/query-evaluation-model-in-detail.md#L117-L123

`let list_of_items` should be `let list_of_hir_items`
or
`for item_def_id in list_of_hir_items { ` should be `for item_def_id in list_of_items { `

**Comment by mark-i-m** [comment]
@SarthakSingh31 Thanks for the report :)

Would you mind opening a PR to fix this? The compiler is constantly under development, so things become outdated sometimes.

**Comment by SarthakSingh31** [comment]
@mark-i-m I created a pull request.
