### ISSUE TITLE
How to accept changes to ui tests?

### ISSUE THREAD

**Issue by kornelski** [rust-lang/rustc-guide#595]
I've changed an error message, and now I need ui tests updated. I know there's a command for this, but I can't find it in the docs.

I'd expect this command to be listed here: https://rust-lang.github.io/rustc-guide/tests/running.html

**Comment by JohnTitor** [comment]
It's documented here: https://rust-lang.github.io/rustc-guide/tests/adding.html#editing-and-updating-the-reference-files

But yeah, it should (also?) be in the running chapter.

**Comment by kornelski** [comment]
Great! The other page answers my question. Unfortunately, googling sent me to the running page.
