### ISSUE TITLE
Downloading artifacts from Rust's CI

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rustc-guide#77]
There is an awesome utility by @kennytm with the short and pithy name `rustup-toolchain-install-master`. What this does is to download the artifacts produced by Rust's CI for a specific SHA1 -- this basically corresponds to the successful landing of some PR -- and then sets them up for your local use. (@kennytm -- does this include `@bors try` artifacts as well?) This is helpful when you want to examine the resulting build of a PR without doing the build yourself.

We should mention this tool somewhere, it's super useful!

**Comment by nikomatsakis** [comment]
(This feels on topic, but maybe it'd be better for forge?)

**Comment by kennytm** [comment]
> does this include `@bors try` artifacts as well?

Yes, because try builds and normal builds are deployed into the same folder on S3.

**Comment by mark-i-m** [comment]
I think we might want to make a separate chapter on infrastructure and pull it boss, crater, CI, and this into that new chapter.

**Comment by dwijnand** [comment]
I think something short and sweet like #216 would already be very useful.
