### ISSUE TITLE
chapter explaining how `Kind` works

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rustc-guide#97]
We don't explain `Kind` at all!

cc @varkor -- want to write it =)

**Comment by varkor** [comment]
I can try to get around to writing something up :+1:

**Comment by nikomatsakis** [comment]
@varkor you rock

**Comment by varkor** [comment]
I've started writing something, but it's a little minimal at the moment: what sort of things would you expect/want to see in such a chapter?

**Comment by mark-i-m** [comment]
Ping @nikomatsakis ^^^

**Comment by mark-i-m** [comment]
Ping @nikomatsakis ^^^ ?

**Comment by nikomatsakis** [comment]
Argh, sorry =)

@varkor I think I would like to see:

- What is the purpose of `Kind`?
- How do I make a `Kind`?
- An example of using `kind.unpack()` works

Actually, some of that might be better as rustc-guide docs, tbh. Always a hard line to figure out where to draw.

**Comment by mark-i-m** [comment]
Ping @varkor ?

**Comment by varkor** [comment]
This is still on my radar, sorry. I'll try to get to it soon.
