### ISSUE TITLE
documentation about feature gates

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rustc-guide#98]
I find myself referencing this forge article a lot:

~https://forge.rust-lang.org/feature-guide.html~
EDIT (mark-i-m): this moved to https://rust-lang.github.io/rustc-guide/implementing_new_features.html

It's ok, but not great. Some things I would like to see covered in rustc-guide instead (and then perhaps remove that article):

- [x] how to add a feature gate in the code
  - [x] how to add a test covering your feature gate
- [ ] how to change for simple syntactic things
- [x] how to do more advanced gates by looking at `sess.features.your_feature_here` as a boolean

**Comment by mark-i-m** [comment]
Also, how to stabilize. And then maybe we can get rid of that forge article too...

**Comment by mark-i-m** [comment]
> how to change for simple syntactic things

@nikomatsakis Could you clarify what you mean by this? Do you mean warning cycles and future compat lints?

**Comment by alecmocatta** [comment]
For anyone else coming here from google and looking for where the above link moved to: https://rust-lang.github.io/rustc-guide/implementing_new_features.html

**Comment by mark-i-m** [comment]
Thanks @alecmocatta 
Updated above.

**Comment by mark-i-m** [comment]
@Centril Do you happen to know what the procedure is for this (from Niko's post above):

> how to change for simple syntactic things

**Comment by Centril** [comment]
@mark-i-m It's documented in https://rust-lang.github.io/rustc-guide/implementing_new_features.html :)

**Comment by mark-i-m** [comment]
Oh, lol ok. I will close this issue then!
